Add v0.1.1

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,8 +17,93 @@ on:
           - "stable"
 
 jobs:
-  placeholder:
+  check-version:
     runs-on: ubuntu-latest
     steps:
-      - name: Placeholder step
-        run: echo "This is a placeholder job for the release workflow."
+      - name: Check version
+        run: |
+          if ! [[ "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Invalid version format. Use X.Y.Z."
+              exit 1
+          fi
+
+  create-version-string:
+    runs-on: ubuntu-latest
+    needs: check-version
+    outputs:
+      version_string: ${{ steps.create_string.outputs.version_string }}
+      nextcloud_version_string: ${{ steps.create_string.outputs.nextcloud_version_string }}
+    steps:
+      - name: Create version string
+        id: create_string
+        run: |
+          if [[ "${{github.event.inputs.releaseType}}" == "develop" ]]; then
+              echo "version_string=${{ github.event.inputs.version }}-dev+${{github.run_number}}" >> "$GITHUB_OUTPUT"
+          elif [[ "${{github.event.inputs.releaseType}}" == "stable" ]]; then
+              echo "version_string=${{ github.event.inputs.version }}" >> "$GITHUB_OUTPUT"
+          else
+              exit 1
+          fi
+
+  check-changelog:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        if: ${{ github.event.inputs.releaseType == 'stable' }}
+        uses: actions/checkout@v4
+
+      - name: Check changelog
+        if: ${{ github.event.inputs.releaseType == 'stable' }}
+        run: |
+          if ! grep -q "## \[${{ github.event.inputs.version }}\] - $(date +%F)" CHANGELOG.md; then
+              echo "Changelog entry for version ${{ github.event.inputs.version }} not found."
+              exit 1
+          fi
+
+  pre-commit:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          submodules: true
+
+      - name: Install Nix
+        uses: cachix/install-nix-action@v27
+
+      - name: Enter devShell and run pre-commit
+        run: |
+          nix develop -c pre-commit run --all-files
+
+  build:
+    needs: pre-commit
+    uses: ./.github/workflows/partial-build.yml
+
+  publish-github-release:
+    runs-on: ubuntu-latest
+    if: ${{ github.event.inputs.releaseType != 'develop' }}
+    needs: [build, create-version-string, check-changelog]
+    permissions:
+      contents: write
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download all build artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: artifacts
+
+      - name: Create body for stable
+        if: ${{ github.event.inputs.releaseType == 'stable' }}
+        run: |
+          perl -ne 'print if /\Q## [${{ needs.create-version-string.outputs.version_string }}]\E/ ... /^[#]{2} /' ./CHANGELOG.md > body.md
+          sed -i '$ d' body.md
+
+      - uses: ncipollo/release-action@v1
+        with:
+          artifacts: "artifacts/**"
+          bodyFile: "body.md"
+          makeLatest: ${{ github.event.inputs.releaseType == 'stable' }}
+          tag: "v${{ needs.create-version-string.outputs.version_string }}"
+          prerelease: ${{ github.event.inputs.releaseType != 'stable' }}
